[general]
id = "br1-154-1"
config_dir = "/etc/scion/AS154"

[metrics]
prometheus = "10.20.3.154:30442"

[features]
experimental_idint = true

[api]
addr = "10.20.3.154:31142"

[log.console]
level = "info"

[router]
num_processors = 1
