// Package baseline loads the per-interface story shaping profile that linkd
// applies at startup and restores on DELETE (generated by
// topology/gen_staticinfo.py, deployed per AS).
package baseline

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/netsys-lab/ietf-scion-testbed/linkd/internal/shape"
)

// Load reads a linkd-baseline.json: {"<ifid>": {"delay_ms": .., "rate_mbit": ..}}.
// Every entry is validated with shape.Validate.
func Load(path string) (map[string]shape.Params, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var m map[string]shape.Params
	if err := json.Unmarshal(raw, &m); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	for ifid, p := range m {
		if err := shape.Validate(p); err != nil {
			return nil, fmt.Errorf("%s: if %s: %w", path, ifid, err)
		}
	}
	return m, nil
}

// ResolveOne resolves a glob to exactly one file.
func ResolveOne(pattern string) (string, error) {
	matches, err := filepath.Glob(pattern)
	if err != nil {
		return "", err
	}
	if len(matches) != 1 {
		return "", fmt.Errorf("%s: %d matches, want exactly 1", pattern, len(matches))
	}
	return matches[0], nil
}
