[general]
id = "sd1-156"
config_dir = "/etc/scion/AS156"

[trust_db]
connection = "/var/lib/scion/sd1-156.trust.db"

[path_db]
connection = "/var/lib/scion/sd1-156.path.db"

[sd]
address = "10.0.0.156:30255"

[metrics]
prometheus = "10.0.0.156:30455"

[features]
experimental_idint = true

[drkey_level2_db]
connection = "/var/lib/scion/sd1-156.drkey_level2.db"

[log.console]
level = "info"
