// Package staticinfo maintains the control service's staticInfoConfig.json:
// the static base document (generated by topology/gen_staticinfo.py) with
// Inter latency/bandwidth overridden from the live tc state, so advertised
// beacon metadata tracks what the link actually does.
package staticinfo

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
	"os/exec"
	"path/filepath"
	"sync"

	"github.com/netsys-lab/ietf-scion-testbed/linkd/internal/shape"
)

type Writer struct {
	BasePath string
	OutPath  string
	Unit     string                  // systemd unit to SIGHUP; empty = skip
	Signal   func(unit string) error // nil = DefaultSignal

	mu                sync.Mutex
	metaFail, hupFail bool
}

// DefaultSignal asks PID1 to SIGHUP the unit (no CAP_KILL needed in linkd).
func DefaultSignal(unit string) error {
	out, err := exec.Command("systemctl", "kill", "--signal=SIGHUP", unit).CombinedOutput()
	if err != nil {
		return fmt.Errorf("systemctl kill %s: %v: %s", unit, err, out)
	}
	return nil
}

// Write rebuilds OutPath from BasePath and the live per-ifid tc state, then
// signals the CS. The base document passes through untouched except
// Latency[ifid].Inter and Bandwidth[ifid].Inter.
func (w *Writer) Write(live map[string]shape.Params) error {
	w.mu.Lock()
	defer w.mu.Unlock()

	doc, err := w.merged(live)
	if err != nil {
		w.metaFail = true
		return err
	}
	if err := writeAtomic(w.OutPath, doc); err != nil {
		w.metaFail = true
		return err
	}
	w.metaFail = false

	if w.Unit == "" {
		w.hupFail = false
		return nil
	}
	sig := w.Signal
	if sig == nil {
		sig = DefaultSignal
	}
	if err := sig(w.Unit); err != nil {
		w.hupFail = true
		return err
	}
	w.hupFail = false
	return nil
}

// Status reports the outcome of the last Write: metadata file written ok,
// CS reload signal delivered ok.
func (w *Writer) Status() (metadataOK, reloadOK bool) {
	w.mu.Lock()
	defer w.mu.Unlock()
	return !w.metaFail, !w.hupFail
}

func (w *Writer) merged(live map[string]shape.Params) ([]byte, error) {
	raw, err := os.ReadFile(w.BasePath)
	if err != nil {
		return nil, err
	}
	var doc map[string]any
	if err := json.Unmarshal(raw, &doc); err != nil {
		return nil, fmt.Errorf("%s: %w", w.BasePath, err)
	}
	for ifid, p := range live {
		if p.DelayMs != nil {
			// Integer microseconds: the deployed CS duration parser
			// (scion fork pkg/private/util/duration.go) is integer-only
			// (strconv.Atoi), so a fractional "%gms" value like "1.3ms"
			// makes json.Unmarshal abort on the whole staticInfoConfig.json.
			setInter(doc, "Latency", ifid, fmt.Sprintf("%dus", int64(math.Round(*p.DelayMs*1000))))
		}
		if p.RateMbit != nil && *p.RateMbit > 0 {
			setInter(doc, "Bandwidth", ifid, uint64(*p.RateMbit*1000))
		}
	}
	return json.MarshalIndent(doc, "", " ")
}

func setInter(doc map[string]any, section, ifid string, v any) {
	sec, _ := doc[section].(map[string]any)
	if sec == nil {
		sec = map[string]any{}
		doc[section] = sec
	}
	entry, _ := sec[ifid].(map[string]any)
	if entry == nil {
		entry = map[string]any{}
		sec[ifid] = entry
	}
	entry["Inter"] = v
}

func writeAtomic(path string, data []byte) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), ".staticinfo-*")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.Write(append(data, '\n')); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Chmod(0o644); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), path)
}
