[general]
id = "cs1-151-1"
config_dir = "/etc/scion/AS151"

[trust_db]
connection = "/var/lib/scion/cs1-151-1.trust.db"

[beacon_db]
connection = "/var/lib/scion/cs1-151-1.beacon.db"

[path_db]
connection = "/var/lib/scion/cs1-151-1.path.db"

[metrics]
prometheus = "10.20.3.151:30452"

[features]
experimental_idint = true

[rpc]
client_protocol = "all"
server_protocol = "all"

[drkey]
prefetch_entries = 10000

[log.console]
level = "info"

[drkey.level1_db]
connection = "/var/lib/scion/cs1-151-1.drkey_level1.db"

[drkey.secret_value_db]
connection = "/var/lib/scion/cs1-151-1.drkey_secret_value.db"

[drkey.delegation]
scmp = [ "127.0.0.1", "::1", "10.20.3.151",]
idint = [ "127.0.0.1", "::1", "10.20.3.151",]

[path]
query_interval = "30s"
