#!/usr/bin/env python3
"""Generate per-AS BIRD 2 configs for the BGP fabric (spec
docs/superpowers/specs/2026-07-11-bgp-fabric-design.md).

eBGP over the existing fd00:fade:<X>:: link addresses; IPv4 rides the same
sessions via RFC 8950 (extended next hop). ASN = SCION AS number. Gao-
Rexford-lite filters from topology.json link_to. wg_ases originate the WG
subnets with device-scoped next-hops (direct hub delivery on the shared L2).

Usage: gen_bird.py [--check]
  --check: regenerate in memory and diff against committed files (exit 1 on drift).
"""
import glob
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

HUB_V4 = "10.20.3.201"
# v6 WG next-hop: the hub holds fd00:beef:<AS>::c8/64 in EACH wg_as's
# segment. BIRD 2.14 keeps a static dormant unless the v6 next-hop lies in a
# connected prefix of the device (onlink does not help; v4 only works
# because 10.20.3.201 is inside eth0's /24 — deploy-surfaced).
WG_ASES = {152, 155, 158, 161}  # deploy_wghub return-route ASes: direct hub L2
WG_V4 = "10.20.5.0/24"
WG_V6 = "fd00:beef:5::/64"

# link_to = this side's view of the neighbor -> (import filter, export filter)
REL_FILTERS = {
    "core":   ("imp_core", "exp_up"),
    "parent": ("imp_provider", "exp_up"),      # neighbor is my provider
    "child":  ("imp_customer", "exp_customer"),  # neighbor is my customer
    "peer":   ("imp_peer", "exp_up"),
}


def strip_host(hostport):
    # "[fd00:fade:1::150]:50000" -> "fd00:fade:1::150"
    return hostport[hostport.index("[") + 1:hostport.index("]")]


def load(root):
    ases = {}
    for f in sorted(glob.glob(os.path.join(root, "config/AS*/topology.json"))):
        with open(f) as fh:
            t = json.load(fh)
        asnum = int(t["isd_as"].split("-")[1])
        ifs = {}
        for br in t["border_routers"].values():
            for ifid, ic in br["interfaces"].items():
                rel = ic["link_to"].lower()
                if rel not in REL_FILTERS:
                    print(f"ERROR: AS{asnum} if {ifid}: unknown link_to "
                          f"{ic['link_to']!r}", file=sys.stderr)
                    sys.exit(1)
                ifs[int(ifid)] = {
                    "local": strip_host(ic["underlay"]["local"]),
                    "remote": strip_host(ic["underlay"]["remote"]),
                    "peer_as": int(ic["isd_as"].split("-")[1]),
                    "link_to": rel,
                }
        ases[asnum] = ifs
    return ases


def validate(ases):
    # Every session must have a mirror on the peer AS (session set == link set x2).
    pairs = set()
    for asnum, ifs in ases.items():
        for i in ifs.values():
            pairs.add((i["local"], i["remote"]))
    for a, b in pairs:
        if (b, a) not in pairs:
            print(f"ERROR: session {a} -> {b} has no mirror", file=sys.stderr)
            sys.exit(1)
    total = sum(len(ifs) for ifs in ases.values())
    if total != 48:
        print(f"ERROR: expected 48 session endpoints (24 links x 2), got {total}",
              file=sys.stderr)
        sys.exit(1)


def render(asnum, ifs, all_as):
    fabric4 = ", ".join([f"10.{n}.0.0/16" for n in all_as] + [WG_V4])
    fabric6 = ", ".join([f"fd00:beef:{n}::/48" for n in all_as] + [WG_V6])
    out = []
    a = out.append
    a(f"# AS{asnum} BGP fabric config -- generated by topology/gen_bird.py; DO NOT EDIT.")
    a("# Regenerate: python3 topology/gen_bird.py    Verify: gen_bird.py --check")
    a("")
    a("log syslog all;")
    a("timeformat protocol iso long;  # linkd parses 'since' as YYYY-MM-DD HH:MM:SS")
    a(f"router id 10.{asnum}.0.1;")
    a("")
    a(f"define FABRIC4 = [ {fabric4} ];")
    a(f"define FABRIC6 = [ {fabric6} ];")
    a("define C_CUST = (65000, 1);  # customer-learned marker; gates exp_up")
    a("")
    a("function fabric_net() {")
    a("  case net.type {")
    a("    NET_IP4: return net ~ FABRIC4;")
    a("    NET_IP6: return net ~ FABRIC6;")
    a("    else: return false;")
    a("  }")
    a("}")
    a("")
    a("# Gao-Rexford-lite: pref customer 300 > peer 250 > core 200 > provider 100;")
    a("# exp_up (to provider/peer/core) exports own + customer-learned only.")
    a("filter imp_customer { if ! fabric_net() then reject; bgp_local_pref = 300; bgp_community.add(C_CUST); accept; }")
    a("filter imp_peer     { if ! fabric_net() then reject; bgp_local_pref = 250; accept; }")
    a("filter imp_core     { if ! fabric_net() then reject; bgp_local_pref = 200; accept; }")
    a("filter imp_provider { if ! fabric_net() then reject; bgp_local_pref = 100; accept; }")
    a("filter exp_customer { if ! fabric_net() then reject; accept; }")
    a("filter exp_up {")
    a("  if ! fabric_net() then reject;")
    a("  if source = RTS_STATIC then accept;")
    a("  if C_CUST ~ bgp_community then accept;")
    a("  reject;")
    a("}")
    a("")
    a("protocol device { }")
    a("")
    a("# krt_prefsrc: fabric-sourced ICMP (traceroute hops) reads as this AS's anchor.")
    a("protocol kernel kernel4 {")
    a(f"  ipv4 {{ export filter {{ if source = RTS_BGP then krt_prefsrc = 10.{asnum}.0.1; accept; }}; }};")
    a("}")
    a("protocol kernel kernel6 {")
    a(f"  ipv6 {{ export filter {{ if source = RTS_BGP then krt_prefsrc = fd00:beef:{asnum}::1; accept; }}; }};")
    a("}")
    a("")
    a("protocol static originate4 {")
    a("  ipv4;")
    a(f"  route 10.{asnum}.0.0/16 blackhole;  # delivery: more-specific on-link /24 (networkd)")
    if asnum in WG_ASES:
        a(f"  route {WG_V4} via {HUB_V4}%eth0;  # WG attendees: direct hub delivery")
    a("}")
    a("protocol static originate6 {")
    a("  ipv6;")
    a(f"  route fd00:beef:{asnum}::/48 blackhole;")
    if asnum in WG_ASES:
        a(f"  route {WG_V6} via fd00:beef:{asnum}::c8;  # hub addr in OUR /64 (see HUB_V4 comment)")
    a("}")
    a("")
    a("protocol bfd {")
    a('  interface "sci*" { interval 500 ms; multiplier 4; };')
    a("}")
    for ifid in sorted(ifs):
        i = ifs[ifid]
        imp, exp = REL_FILTERS[i["link_to"]]
        a("")
        a(f"protocol bgp bgp_if{ifid} {{")
        a(f"  description \"AS{i['peer_as']} ({i['link_to']}) ifid {ifid}\";")
        a(f"  local {i['local']} as {asnum};")
        a(f"  neighbor {i['remote']} as {i['peer_as']};")
        a("  bfd on;")
        a(f"  ipv4 {{ import filter {imp}; export filter {exp}; extended next hop on; }};")
        a(f"  ipv6 {{ import filter {imp}; export filter {exp}; }};")
        a("}")
    a("")
    return "\n".join(out)


def main():
    ases = load(ROOT)
    validate(ases)
    all_as = sorted(ases)
    files = {}
    for asnum, ifs in ases.items():
        files[os.path.join(ROOT, f"config/AS{asnum}/bird.conf")] = render(asnum, ifs, all_as)
    if "--check" in sys.argv[1:]:
        drift = []
        for p, text in sorted(files.items()):
            if not os.path.exists(p):
                drift.append(p)
                continue
            with open(p) as fh:
                if fh.read() != text:
                    drift.append(p)
        if drift:
            for p in drift:
                print(f"DRIFT: {os.path.relpath(p, ROOT)}", file=sys.stderr)
            sys.exit(1)
        print(f"OK: {len(files)} bird.conf generated, files match")
    else:
        for p, text in files.items():
            with open(p, "w") as f:
                f.write(text)
        print(f"OK: {len(files)} bird.conf written")


if __name__ == "__main__":
    main()
