[general]
id = "br1-157-1"
config_dir = "/etc/scion/AS157"

[metrics]
prometheus = "10.20.3.157:30442"

[features]
experimental_idint = true

[log.console]
level = "info"

[router]
num_processors = 1
batch_size = 64
