[general]
id = "sd1-157"
config_dir = "gen/AS157"

[trust_db]
connection = "gen-cache/sd1-157.trust.db"

[path_db]
connection = "gen-cache/sd1-157.path.db"

[sd]
address = "127.0.0.67:30255"

[tracing]
enabled = true
debug = true
agent = "172.17.0.1:6831"

[metrics]
prometheus = "127.0.0.67:30455"

[features]
experimental_idint = true

[api]
addr = "127.0.0.67:30955"

[drkey_level2_db]
connection = "gen-cache/sd1-157.drkey_level2.db"

[log.console]
level = "debug"
