[general]
id = "br1-153-1"
config_dir = "/etc/scion/AS153"

[metrics]
prometheus = "10.20.3.153:30442"

[features]
experimental_idint = true

[api]
addr = "10.20.3.153:31142"

[log.console]
level = "info"

[router]
num_processors = 1
