[general]
id = "br1-150-1"
config_dir = "/etc/scion/AS150"

[metrics]
prometheus = "10.20.3.150:30442"

[features]
experimental_idint = true

[log.console]
level = "info"

[router]
num_processors = 1
