[general]
id = "br1-160-1"
config_dir = "/etc/scion/AS160"

[metrics]
prometheus = "10.20.3.160:30442"

[features]
experimental_idint = true

[log.console]
level = "info"

[router]
num_processors = 1
