[general]
id = "cs1-160-1"
config_dir = "/etc/scion/AS160"

[trust_db]
connection = "/var/lib/scion/cs1-160-1.trust.db"

[beacon_db]
connection = "/var/lib/scion/cs1-160-1.beacon.db"

[path_db]
connection = "/var/lib/scion/cs1-160-1.path.db"

[metrics]
prometheus = "10.0.0.161:30452"

[features]
experimental_idint = true

[rpc]
client_protocol = "all"
server_protocol = "all"

[drkey]
prefetch_entries = 10000

[log.console]
level = "info"

[drkey.level1_db]
connection = "/var/lib/scion/cs1-160-1.drkey_level1.db"

[drkey.secret_value_db]
connection = "/var/lib/scion/cs1-160-1.drkey_secret_value.db"

[drkey.delegation]
scmp = [ "127.0.0.1", "::1", "10.0.0.161",]
idint = [ "127.0.0.1", "::1", "10.0.0.161",]
