[general]
id = "sd1-160"
config_dir = "gen/AS160"

[trust_db]
connection = "gen-cache/sd1-160.trust.db"

[path_db]
connection = "gen-cache/sd1-160.path.db"

[sd]
address = "127.0.0.91:30255"

[tracing]
enabled = true
debug = true
agent = "172.17.0.1:6831"

[metrics]
prometheus = "127.0.0.91:30455"

[features]
experimental_idint = true

[api]
addr = "127.0.0.91:30955"

[drkey_level2_db]
connection = "gen-cache/sd1-160.drkey_level2.db"

[log.console]
level = "debug"
