[general]
id = "sd1-160"
config_dir = "/etc/scion/AS160"

[trust_db]
connection = "/var/lib/scion/sd1-160.trust.db"

[path_db]
connection = "/var/lib/scion/sd1-160.path.db"

[sd]
address = "10.20.3.160:30255"

[metrics]
prometheus = "10.20.3.160:30455"

[features]
experimental_idint = true

[drkey_level2_db]
connection = "/var/lib/scion/sd1-160.drkey_level2.db"

[log.console]
level = "info"
