[general]
id = "sd1-158"
config_dir = "/etc/scion/AS158"

[trust_db]
connection = "/var/lib/scion/sd1-158.trust.db"

[path_db]
connection = "/var/lib/scion/sd1-158.path.db"

[sd]
address = "10.20.3.158:30255"

[metrics]
prometheus = "10.20.3.158:30455"

[features]
experimental_idint = true

[drkey_level2_db]
connection = "/var/lib/scion/sd1-158.drkey_level2.db"

[log.console]
level = "info"
