[general]
id = "br1-155-1"
config_dir = "/etc/scion/AS155"

[metrics]
prometheus = "10.20.3.155:30442"

[features]
experimental_idint = true

[log.console]
level = "info"

[router]
num_processors = 1
batch_size = 64
